#!/bin/sh
#
# chkconfig: - 80 45
# description: Starts and stops Cassandra
# update deamon path to point to the cassandra executable

DEAMON=/usr/local/cassandra/bin/cassandra

start() {
        echo -n "Starting Cassandra... "
        $DEAMON -p /var/run/cassandra.pid
        echo "OK"
        return 0
}

stop() {
        echo -n "Stopping Cassandra... "
        kill $(cat /var/run/cassandra.pid)
        echo "OK"
        return 0
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?